### ISSUE TITLE
How to access GetExtension in c# like c++

### ISSUE THREAD

**Issue by Mirage1089** [jskeet/protobuf-csharp-port#109]
syntax = "proto3";
import "google/protobuf/descriptor.proto";
extend google.protobuf.MessageOptions {
      int32 field1 = 999;
}

message AnyMessage {
      option (field1) = 10987;
}

int value = AnyMessage::descriptor()->options().GetExtension(field1);
how can I do this in c#?

**Comment by jskeet** [comment]
Firstly, this project (protobuf-csharp-port) doesn't support proto3.

The proto3 C# support is in the main protobuf project: https://github.com/google/protobuf
That said, C# there doesn't yet support retrieving options. I raised https://github.com/google/protobuf/issues/2143 a while ago to track the fact that we _want_ to do this, but we haven't done so yet.

**Comment by Mirage1089** [comment]
Thank you for your reply. Really a bad news. Basically, I need to set a default value for a field in the proto file, which was possible in proto2 but in proto3 it is deprecated . I don't know why google removed this default feature. Is it possible to solve set default value in another way using proto3 and which will work in every platform like c++, c# ?

**Comment by jskeet** [comment]
No, proto3 just doesn't support default values.
