### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by Hummel-Wang** [jskeet/protobuf-csharp-port#110]
I am a .net coder. There is a issue when client decoding , The code is as follows:

 byte[] body = bodyBuffer.CloneRange(offset, length); // big file 500M
 DefeatMessage message = DefeatMessage.ParseFrom(body);

my questions is as follows:
1.This demand can be achieved? 
2.If can, What should I do?
  
TKS

**Comment by jskeet** [comment]
Well it entirely depends on what's in `DefeatMessage`. Given that the protobuf encoding is fairly efficient, I wouldn't be at all surprised if that ends up running out of memory, particularly if it needs to create lots and lots of message objects. Ideally, you should design your system to work on a more streaming fashion, so you can work with a smaller portion of the total problem at a time.

**Comment by Hummel-Wang** [comment]
jskeet， Thank you for you reply.
1. The DefeatMessage.proto file is as follows:
import "BackMessage.proto";
import "CallMessage.proto";
message DefeatMessage {
  enum Type { CallMessage = 1; BackMessage = 2; }

  optional Type type = 1;

  optional CallMessage callMessage = 2;
  optional BackMessage backMessage = 3;
  optional bytes body = 4;
}
2. The BackMessage is as follows:
message BackMessage {

  optional string content = 1;

}
3. The CallMessage is like the BackMessage.

TKS

**Comment by jskeet** [comment]
So if you've got a 500MB `DefeatMessage`, that suggests part of that is pretty huge. Note that if it's the `BackMessage.content` that's large, then if it's all ASCII text, it will be twice as large when in memory as a `string` in .NET.

**Comment by Hummel-Wang** [comment]
jskeet, i`m sorry. I did not make it clear. 
In fact, big data comes from DefeatMessages' body. I'm sorry again.

**Comment by jskeet** [comment]
Right, well I'd expect that to be okay if you have enough memory - basically, it should be trying to allocate a byte array of the appropriate size. If you've got enough memory for that, it will work... otherwise it won't. There's not a lot protobuf can do if you need a bigger `ByteString` than you have memory for.
