### ISSUE TITLE
src/ProtoBench/Program.cs(254,65): error CS0103: The name `JsonReaderWriterFactory' does not exist in the current context

### ISSUE THREAD

**Issue by Reinoal** [jskeet/protobuf-csharp-port#112]
using System.Runtime.Serialization Json does not exist in the namespace `System.Runtime.Serialization'. Are you missing an assembly reference?

**Comment by jskeet** [comment]
Firstly, please note that this repository is basically unmaintained. I would strongly advise moving over to Google.Protobuf, at https://github.com/protocolbuffers/protobuf. I won't be spending much time on this issue.

That being said, I've just cloned the repo myself and built it - it worked fine after I'd unloaded proto-gen-cs and the corresponding test project, and switch from Debug_Silverlight to Debug as the configuration.

It does target .NET 3.5 though - do you definitely have the .NET 3.5 targeting pack installed?
